### ISSUE TITLE
Default "End" between end of rains and end of season

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/rpicsa#3]
@rdstern another, hopefully quick question for you if you don't mind getting a little involved in the epicsa work

We have end of rains and end of season. Which should be the default option when calculating:

* Length of the season (`seasonal_length`)
* Number of rainy days within a season, and sum of rainfall (`seasonal_rain`)
* The probabilities of crop success for given planting maturity lengths, seasonal total rainfall requirements, and planting dates (`crop_success_probabilities`)

Thanks!

**Comment by rdstern** [comment]
Some backgro0und is as follows:
We used to just have the end of the season calculated through the simple water balance.  That worked fine in West Africa, where August was always pretty rainy.
In Southen Africa the simple water balance didn't work well.  That's because, in uni-modal Southern Africa February is the equivalent of August in West Africa.  But February was sometimes different as there were occasionally long dry spells in February - so the water balance then occasionally ended in what  everyone would agree was still the middle of the season.

(It is possible that the reducing evaporation that you are about to add to R-Instat might help alleviate this problem.  I am not convinced.)

So we moved to start using a definition of the end of the rains from a paper in Zimbabwe in 2011.  That's the end of the rains definition in R-Instat now.

Then we were still asked for the end of the season - in a water balance way - and now start looking for the end of the season, with water balance (or reducing evaporation), but starting from the end of the rains.

SoI would use End of Season.  I think for each of the above.
